//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckShow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string Container_Ip {
            get {
                return ((string)(this["Container_Ip"]));
            }
            set {
                this["Container_Ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12011")]
        public int Container_Port {
            get {
                return ((int)(this["Container_Port"]));
            }
            set {
                this["Container_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\cc\\Desktop\\Image")]
        public string Container_ImagePath {
            get {
                return ((string)(this["Container_ImagePath"]));
            }
            set {
                this["Container_ImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string Container_Lane {
            get {
                return ((string)(this["Container_Lane"]));
            }
            set {
                this["Container_Lane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public string Container_Plate_Name {
            get {
                return ((string)(this["Container_Plate_Name"]));
            }
            set {
                this["Container_Plate_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\cc\\Desktop\\Image")]
        public string Container_ChediPath {
            get {
                return ((string)(this["Container_ChediPath"]));
            }
            set {
                this["Container_ChediPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string UVSSIp {
            get {
                return ((string)(this["UVSSIp"]));
            }
            set {
                this["UVSSIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20145")]
        public int UVSSPort {
            get {
                return ((int)(this["UVSSPort"]));
            }
            set {
                this["UVSSPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123")]
        public string Exit_Password {
            get {
                return ((string)(this["Exit_Password"]));
            }
            set {
                this["Exit_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string ContainerDLL_Ip {
            get {
                return ((string)(this["ContainerDLL_Ip"]));
            }
            set {
                this["ContainerDLL_Ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12011")]
        public int ContainerDLL_Port {
            get {
                return ((int)(this["ContainerDLL_Port"]));
            }
            set {
                this["ContainerDLL_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ContainerDLL_Intervals {
            get {
                return ((int)(this["ContainerDLL_Intervals"]));
            }
            set {
                this["ContainerDLL_Intervals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string LocalIp_bing {
            get {
                return ((string)(this["LocalIp_bing"]));
            }
            set {
                this["LocalIp_bing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12088")]
        public int LocalPort_bing_1 {
            get {
                return ((int)(this["LocalPort_bing_1"]));
            }
            set {
                this["LocalPort_bing_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12089")]
        public int LocalPort_bing_2 {
            get {
                return ((int)(this["LocalPort_bing_2"]));
            }
            set {
                this["LocalPort_bing_2"] = value;
            }
        }
    }
}
